- platform: mqtt
  name: "mk"
  state_topic: "$SYS/broker/connection/mqtt.mk/state"
  payload_on: '1'
  payload_off: '0'
     
- platform: template
  sensors:
    tv:
      friendly_name: 'TV'
      value_template: '{{ states.sensor.tv.state|int > 10 }}'
  

- platform: mqtt
  state_topic: dummy/floorplan/sensor
  name: Floorplan

- platform: mqtt
  name: "motion_bar"
  state_topic: "PIR/bar"
  device_class: motion
  
- platform: mqtt
  name: "motion_spot"
  state_topic: "PIR/spot"
  device_class: motion

- platform: mqtt
  name: "motion_table"
  state_topic: "PIR/table"
  device_class: motion
  
- platform: workday
  country: !secret uk
