homeassistant:  
  whitelist_external_dirs:
    - /config/storj
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
      - 192.168.0.0/24
      - 172.19.0.0/24
      allow_bypass_login: true
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 185
  # metric for Metric, imperial for Retarted
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  # Customization file
  customize: !include customizes.yaml
  packages: !include_dir_named packages/
  
# panel_iframe:
#   editor:
#     title: IDE
#     icon: mdi:code-braces
#     url: !secret url

# Enables the frontend
frontend:
  themes: !include themes.yaml
  extra_html_url:
    - /local/custom_ui/state-card-floorplan.html
    # - http://cloud9.kpu.ro/ide.html

panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml

vacuum:
  - platform: xiaomi_miio
    host: !secret vaccum
    name: 'Harry Potter'
    token: !secret vaccum_token

xiaomi_aqara:
  gateways:
  - mac: !secret xg_mac
    key: !secret xg_key
    host: !secret xg_host

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: home-assistant-1
#  keepalive: 60
  username: !secret mqtt_user
  password: !secret mqtt_password
  discovery: true
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'
# Enables configuration UI
config:

http:
  #ssl_certificate: !secret ssl_certificate
  #ssl_key: !secret ssl_key
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: !secret base_url

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true
  
# hassio:

# Discover some devices automatically
discovery:
  ignore:
    - homekit
#    - roku 
    - yeelight

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:
  exclude:
    entities:
      - automation.location
      - input_select.location
      - binary_sensor.motion_spot
      - binary_sensor.motion_table
      - light.hallway1
      - light.hallway1_light
      - light.hallway2
      - light.hallway2_light
      - light.hallway3
      - light.hallway3_light
      - group.guster
      - automation.remote_roku

logger:
  default: info
  logs:
    sensor.laptop: warning
    pychromecast.socket_client: fatal

influxdb:
  exclude:
    entities:
       - sensor.time
       - sun.sun

recorder:
  db_url: !secret db_url
  purge_keep_days: 2

#system_health:

default_config:

alert:
  motion_battery:
    name: Sensor Battery is Low
    entity_id: sensor.battery
    repeat: 10
    notifiers:
      - hass

person:
  - name: Z
    id: Z
    device_trackers:
      - device_tracker.z
      - device_tracker.z_phone
  - name: !secret she
    id: ro
    device_trackers:
      - device_tracker.r
      - device_tracker.rdell
      - device_tracker.rpc
      - device_tracker.r_phone

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

shopping_list:
roku:
  - host: !secret roku_host
# Plex
media_player:
  - platform: spotify
    client_id: !secret client_id
    client_secret: !secret client_secret
  - platform: plex
    # entity_namespace: 'plex'
    # include_non_clients: true
    scan_interval: 5
    # use_custom_entity_ids: true
    # use_episode_art: true

  - platform: androidtv
    name: FireTV
    host: !secret firetv_host
    adbkey: "/config/adb/adbkey"
    apps:
      com.amazon.tv.launcher: "Fire TV"
      com.plexapp.android: "Plex"

device_tracker:
  # - platform: snmp
    # host: !secret snmp_host
    # community: !secret snmp_community
    # baseoid: !secret snmp_baseoid
    # interval_seconds: 30
    # consider_home: 60
  - platform: nmap_tracker
    hosts:
      - !secret nmap_hosts
    home_interval: 5
    interval_seconds: 20
  - platform: unifi
    host: unifi
    username: !secret unifi_user
    password: !secret unifi_pass
    verify_ssl: false
    interval_seconds: 30
    monitored_conditions:
      - rssi
      - ap_mac
# googlehome:
#   devices:
#   - host: !secret ghome
#     rssi_threshold: -100
#     track_devices: true
#     device_types: 2

telegram_bot:
  - platform: polling
    api_key: !secret telegram
    parse_mode: html
    allowed_chat_ids:
      - !secret chat_id

yeelight:
  devices:
    !secret Kitchen:
      name: Kitchen
      transition: 1000
      save_on_change: False
    !secret Kitchen_strip:
      name: Kitchen Strip
      transition: 1000
      save_on_change: False
    !secret WC:
      name: WC
      transition: 1000
      save_on_change: False
    !secret Bob:
      name: Bob
      transition: 1000
      save_on_change: False
    !secret Bathroom:
      name: Bathroom
      transition: 1000
      save_on_change: False
    !secret DarkRoom:
      name: DarkRoom
      transition: 1000
      save_on_change: False
    !secret LightRoom:
      name: LightRoom
      transition: 1000
      save_on_change: False
    !secret Bedroom:
      name: Bedroom
      transition: 1000
      save_on_change: False

notify: !include notify.yaml

media_extractor:

input_datetime: !include input_datetime.yaml

input_text:
  url:
    name: URL
    initial: URL

climate:
  - platform: generic_thermostat
    name: Living
    heater: switch.ac
    target_sensor: sensor.temperature_living
    min_temp: 24
    max_temp: 27
    ac_mode: true
    target_temp: 26
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3
    initial_hvac_mode: "off"
    precision: 0.5

input_boolean: !include input_boolean.yaml

cloud: !include cloud.yaml

scene: !include scenes.yaml

automation: !include automation.yaml

light: !include lights.yaml

switch: !include switches.yaml

sensor: !include sensors.yaml

binary_sensor: !include binary_sensor.yaml

group: !include groups.yaml

script: !include scripts.yaml

input_select: !include input_select.yaml

shell_command: !include shell_command.yaml

zone: !include zone.yaml
