- platform: group
  name: Kitchen Day
  entities:
    - light.kitchen

- platform: group
  name: Kitchen Night
  entities:
    - light.bar
    - light.kitchen_strip

- platform: mqtt
  name: "Hallway"
  state_topic: "zigbee2mqtt/Hallway"
  command_topic: "zigbee2mqtt/Hallway/set"
  availability_topic: "zigbee2mqtt/bridge/state"
  brightness: true
  color_temp: true
  schema: "json"

- platform: mqtt
  name: "Hallway1"
  state_topic: "zigbee2mqtt/Hallway1"
  command_topic: "zigbee2mqtt/Hallway1/set"
  availability_topic: "zigbee2mqtt/bridge/state"
  brightness: true
  color_temp: true
  schema: "json"

- platform: mqtt
  name: "Hallway2"
  state_topic: "zigbee2mqtt/Hallway2"
  command_topic: "zigbee2mqtt/Hallway2/set"
  availability_topic: "zigbee2mqtt/bridge/state"
  brightness: true
  color_temp: true
  schema: "json"

- platform: mqtt
  name: "Hallway3"
  state_topic: "zigbee2mqtt/Hallway3"
  command_topic: "zigbee2mqtt/Hallway3/set"
  availability_topic: "zigbee2mqtt/bridge/state"
  brightness: true
  color_temp: true
  schema: "json"

- platform: mqtt
  name: "Table"
#  state_topic: "stat/table/POWER"
#  state_topic: "home/table/tele/STATE"
#  state_value_template: "{{ value_json.POWER }}"
  state_topic: "table/stat/POWER"
  command_topic: "table/cmnd/POWER"
  availability_topic: "table/tele/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Bar"
  state_topic: "stat/bar/RESULT"
  state_value_template: "{{value_json.POWER}}"
  command_topic: "cmnd/bar/POWER"
  availability_topic: "tele/bar/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "spot"
  state_topic: "stat/spot/RESULT"
  state_value_template: "{{value_json.POWER}}"
  command_topic: "cmnd/spot/POWER"
  availability_topic: "tele/spot/LWT"
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Entrance"
  state_topic: "home/niggers/hallway1/set"
  command_topic: "home/niggers/hallway1/set"
  payload_on: 1
  payload_off: 0
  optimistic: false
  qos: 0
  retain: true
