- platform: template
  switches:
    projector:
      value_template: "{{ states.sensor.t_power.state|int > 200 }}"
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.projector_ir
      turn_off:
      - service: switch.turn_off
        entity_id: switch.projector_ir
      - service: switch.turn_off
        entity_id: switch.projector_ir
      - service: switch.turn_off
        entity_id: switch.projector_ir

# - platform: mqtt
#   name: "HTPC"
#   state_topic: "stat/htpc/RESULT"
#   command_topic: "cmnd/htpc/POWER"
#   availability_topic: "tele/htpc/LWT"
#   qos: 1
#   payload_on: "ON"
#   payload_off: "OFF"
#   payload_available: "Online"
#   payload_not_available: "Offline"
#   retain: false

- platform: mqtt
  name: "Socket"
  state_topic: "stat/socket/POWER"
  command_topic: "cmnd/socket/POWER"
  availability_topic: "tele/socket/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

- platform: mqtt
  name: "Trantor power"
  state_topic: "stat/trantor/POWER"
  command_topic: "cmnd/trantor/POWER"
  availability_topic: "tele/trantor/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

- platform: broadlink
  host: !secret broadlink_host
  mac: !secret broadlink_mac
  timeout: 15
  switches:
    projector_ir:
      friendly_name: "Projector"
      command_on: 'JgBYAAABJ5cQFRE5ERUQFRE5EToRFBEUEToRFBE5EToRFBEUEToROREVEDoRFBEVEBURFBEUERQROhITEjkQOhE6EDoROhA6EQAFDQABKEwQAAxUAAEnTBEADQU='
      command_off: 'JgBYAAABKJYQFRE5ERUQFRE5EToRFBEUEToQFRE5EToSExEUEToRORIUEDoROhA6ERUQOhAVERQROhAVERQRFRA6EhMROhA6EQAFDQABKEsRAAxTAAEoSxEADQU='
    hdmi1:
      friendly_name: "HDMI1"
      command_on: 'JgBYAAABKJUSFBA6EhMSExI5EjkRFBEUEToQFRE5EjkRFBEUEjkRORIUETkSOREUEjgSExIUERQSOREUERQRORIUEjgSORE5EgAFDQABJ0wSAAxTAAEnTBIADQU='
      command_off: ''
    hdmi2:
      friendly_name: "HDMI2"
      command_on: 'JgCoAAABJ5YSFBA6ERQSFBE5EToRFBITEjkRFBE5EjkSExEUEjkRORIUERQRFBITEjkSOBIUEBUROhA6EToRORITEhQRORI4EQAFDgABJ0wRAAxUAAEoSxIADFMAASdMEgAMUwABJ0wSAAxSAAEnTREADFMAASdMEgAMUwABKEsSAAxSAAEnTREADFMAASdNEQAMUwABJ0wRAAxVAAEnTBEADFQAASdMEgANBQ=='
      command_off: ''
    ac:
      friendly_name: "AC"
      command_on: 'JgBAAAABGYgPNA4UDRQNFA41DhMOFA0UDRQOFA0UDRQNFA4UDRQNFA4UDRQNNg01DhQNNQ4UDRQNFA41DTYNNQ4ADQUAAAAAAAAAAA=='
      command_off: 'JgBAAAABGogPNA0UDhQNFA01DhQNFA4UDTUNNg0UDRQOFA0UDRQOFA0UDRQOFA0UDRQONQ0UDjUNFA4TDhQNNQ4ADQUAAAAAAAAAAA=='

- platform: mqtt
  name: "Riki's food"
  state_topic: "home/riki/stat"
  command_topic: "home/riki"
  qos: 0
  payload_on: "push"
  payload_off: "off"
  retain: true

# The following switch wakes up the coffee machine
- platform: mqtt
  name: "Coffee Machine"
  state_topic: "home/tweek/status"
  command_topic: "home/tweek/cmd"
  qos: 2
  payload_on: "0"
  payload_off: "9"
  value_template: >
        {% if value == 'ready' %}
        0
        {% elif value == 'standby' %}
        9
        {% endif %}

# The following switches makes coffee      
- platform: mqtt
  name: "Espresso"
  state_topic: "home/tweek/status"
  command_topic: "home/tweek/cmd"
  qos: 2
  payload_on: "1"
  payload_off: ""
  value_template: '{{ value == "espresso" }}'

- platform: mqtt
  name: "Coffee"
  state_topic: "home/tweek/status"
  command_topic: "home/tweek/cmd"
  qos: 2
  payload_on: "2"
  payload_off: ""
  value_template: '{{ value == "coffee" }}'

# docker containers
- platform: rest
  resource: http://127.0.0.1:8126/container/couchpotato
  name: Couchpotato
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://127.0.0.1:8126/container/cron
  name: Cron
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://127.0.0.1:8126/container/dockermon
  name: DockerMon
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://127.0.0.1:8126/container/grafana
  name: Grafana
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://127.0.0.1:8126/container/hass
  name: HASS
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://127.0.0.1:8126/container/influxdb
  name: InfluxDB
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://127.0.0.1:8126/container/letsencrypt
  name: Letsencrypt
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://127.0.0.1:8126/container/mariadb
  name: MariaDB
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://127.0.0.1:8126/container/mqtt
  name: MQTT
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://127.0.0.1:8126/container/nextcloud
  name: Nextcloud
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://127.0.0.1:8126/container/nginx
  name: nginx
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://127.0.0.1:8126/container/openvpn
  name: OpenVpn
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://127.0.0.1:8126/container/plex
  name: Plex
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://127.0.0.1:8126/container/portainer
  name: Portainer
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://127.0.0.1:8126/container/proxy
  name: Proxy
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://127.0.0.1:8126/container/redis
  name: redis
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://127.0.0.1:8126/container/sickrage
  name: Sickrage
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://127.0.0.1:8126/container/smokeping
  name: Smokeping
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://127.0.0.1:8126/container/storagenode
  name: Storagenode
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://127.0.0.1:8126/container/storj1
  name: Storj1
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://127.0.0.1:8126/container/storj2
  name: Storj2
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://127.0.0.1:8126/container/storj3
  name: Storj3
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://127.0.0.1:8126/container/tautulli
  name: Tautulli
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://127.0.0.1:8126/container/transmission
  name: Transmission
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://127.0.0.1:8126/container/unifi
  name: Unifi
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://127.0.0.1:8126/container/z2m
  name: Z2M
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
