# - platform: command_line
  # switches:
    # door:
      # friendly_name: Door Lock
      # command_on: /bin/bash -c "/config/adb/adb.sh shell input keyevent 26&&sleep 0.2&&/config/adb/adb.sh shell input swipe 360 1000 150 1000;/config/adb/adb.sh shell input keyevent 26"
      # command_off: /bin/bash -c "/config/adb/adb.sh shell input keyevent 26&&sleep 0.2&&/config/adb/adb.sh shell input swipe 360 1000 580 1000;/config/adb/adb.sh shell input keyevent 26"
      # command_state: /bin/bash -c "/config/adb/adb.sh shell cat /storage/sdcard0/Android/data/com.xiaomi.smarthome/files/SherlockLog/$(date +%Y%m%d.log)|grep mOperateCommandType|tail -1| grep -oP '(?<=mOperateCommandType:).*?(?=\r)'"
      # value_template: '{{ value == "Lock" }}'

- platform: mqtt
  name: "Socket"
  state_topic: "stat/socket/POWER"
  command_topic: "cmnd/socket/POWER"
  availability_topic: "tele/socket/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

- platform: mqtt
  name: "Trantor power"
  state_topic: "stat/trantor/POWER"
  command_topic: "cmnd/trantor/POWER"
  availability_topic: "tele/trantor/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

- platform: broadlink
  host: !secret broadlink_host
  mac: !secret broadlink_mac
  timeout: 15
  switches:
    projector:
      friendly_name: "Projector"
      command_on: 'JgBYAAABJpURFBEUERQROREUERQQFRAUETkROhETERQROREUERQRFBE5EjgROREUERQRFBAVEDoRExEUERQRORI4ETkRORITEQAFswABJkwQAAxXAAEmTBAADQU='
      command_off: 'JgBYAAABJpURFBEUERQROREUERQQFRAUETkROhETERQROREUERQRFBE5EjgROREUERQRFBAVEDoRExEUERQRORI4ETkRORITEQAFswABJkwQAAxXAAEmTBAADQU='
    projector_esc:
      friendly_name: "Projector ESC"
      command_on: 'JgBQAAABJpUSExEUERQROREUEBUQFBEUETkROREUEhMROREUERQRFBE5ERQRORE5ETkRFBE5ERQQFRA6EBUQFBEUETkRFBE5EQAFswABJkwQAA0FAAAAAAAAAAA='
      command_off: 'JgBYAAABJpURFBEUERQROREUERQQFRAUETkROhETERQROREUERQRFBE5EjgROREUERQRFBAVEDoRExEUERQRORI4ETkRORITEQAFswABJkwQAAxXAAEmTBAADQU='
    ac:
      friendly_name: "AC"
      command_on: 'JgBAAAABGYgPNA4UDRQNFA41DhMOFA0UDRQOFA0UDRQNFA4UDRQNFA4UDRQNNg01DhQNNQ4UDRQNFA41DTYNNQ4ADQUAAAAAAAAAAA=='
      command_off: 'JgBAAAABGogPNA0UDhQNFA01DhQNFA4UDTUNNg0UDRQOFA0UDRQOFA0UDRQOFA0UDRQONQ0UDjUNFA4TDhQNNQ4ADQUAAAAAAAAAAA=='
  # The following switch orders food
# - platform: command_line
  # switches:
    # fortys:
      # command_on: " "
      # command_off: " "
      # command_state: " "
      # #value_template: '{{ value == "1" }}'
      # friendly_name: "Forty Cowboy Pizza"

# - platform: command_line
  # switches:
    # caruso:
      # command_on: " "
      # command_off: " "
      # command_state: " "
      # #value_template: '{{ value == "1" }}'
      # friendly_name: "Caruso Contadina Pizza"

# - platform: command_line
  # switches:
    # holiday:
      # command_on: " "
      # command_off: " "
      # command_state: " "
      # #value_template: '{{ value == "1" }}'
      # friendly_name: "Holiday Zebra"

- platform: mqtt
  name: "Riki's food"
  state_topic: "home/riki/stat"
  command_topic: "home/riki"
  qos: 0
  payload_on: "push"
  payload_off: "off"
  retain: true

# The following switch wakes up the coffee machine
- platform: mqtt
  name: "Coffee Machine"
  state_topic: "home/tweek/status"
  command_topic: "home/tweek/cmd"
  qos: 2
  payload_on: "0"
  payload_off: "9"
  value_template: >
        {% if value == 'on' %}
        0
        {% elif value == 'off' %}
        9
        {% endif %}

# The following switches makes coffee      
- platform: mqtt
  name: "Espresso"
  state_topic: "home/tweek/status"
  command_topic: "home/tweek/cmd"
  qos: 2
  payload_on: "1"
  payload_off: "9"
  value_template: >
        {% if value == 'espresso' %}
        1
        {% elif value == 'off' %}
        9
        {% endif %}

- platform: mqtt
  name: "Coffee"
  state_topic: "home/tweek/status"
  command_topic: "home/tweek/cmd"
  qos: 2
  payload_on: "2"
  payload_off: ""
  value_template: '{{ value == "coffee" }}'

