- platform: template
  switches:
    projector:
      value_template: "{{ states.sensor.t_power.state|int > 200 }}"
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.projector_ir
      turn_off:
      - service: switch.turn_off
        entity_id: switch.projector_ir
      - service: switch.turn_off
        entity_id: switch.projector_ir
      - service: switch.turn_off
        entity_id: switch.projector_ir

- platform: mqtt
  name: "Socket"
  state_topic: "stat/socket/POWER"
  command_topic: "cmnd/socket/POWER"
  availability_topic: "tele/socket/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

- platform: mqtt
  name: "Trantor power"
  state_topic: "stat/trantor/POWER"
  command_topic: "cmnd/trantor/POWER"
  availability_topic: "tele/trantor/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

- platform: broadlink
  host: !secret broadlink_host
  mac: !secret broadlink_mac
  timeout: 15
  switches:
    projector_ir:
      friendly_name: "Projector"
      command_on: 'JgBYAAABJ5cQFRE5ERUQFRE5EToRFBEUEToRFBE5EToRFBEUEToROREVEDoRFBEVEBURFBEUERQROhITEjkQOhE6EDoROhA6EQAFDQABKEwQAAxUAAEnTBEADQU='
      command_off: 'JgBYAAABKJYQFRE5ERUQFRE5EToRFBEUEToQFRE5EToSExEUEToRORIUEDoROhA6ERUQOhAVERQROhAVERQRFRA6EhMROhA6EQAFDQABKEsRAAxTAAEoSxEADQU='
    # projector_esc:
    #   friendly_name: "Projector ESC"
    #   command_on: 'JgBQAAABJpUSExEUERQROREUEBUQFBEUETkROREUEhMROREUERQRFBE5ERQRORE5ETkRFBE5ERQQFRA6EBUQFBEUETkRFBE5EQAFswABJkwQAA0FAAAAAAAAAAA='
    #   command_off: 'JgBYAAABJpURFBEUERQROREUERQQFRAUETkROhETERQROREUERQRFBE5EjgROREUERQRFBAVEDoRExEUERQRORI4ETkRORITEQAFswABJkwQAAxXAAEmTBAADQU='
    ac:
      friendly_name: "AC"
      command_on: 'JgBAAAABGYgPNA4UDRQNFA41DhMOFA0UDRQOFA0UDRQNFA4UDRQNFA4UDRQNNg01DhQNNQ4UDRQNFA41DTYNNQ4ADQUAAAAAAAAAAA=='
      command_off: 'JgBAAAABGogPNA0UDhQNFA01DhQNFA4UDTUNNg0UDRQOFA0UDRQOFA0UDRQOFA0UDRQONQ0UDjUNFA4TDhQNNQ4ADQUAAAAAAAAAAA=='

- platform: mqtt
  name: "Riki's food"
  state_topic: "home/riki/stat"
  command_topic: "home/riki"
  qos: 0
  payload_on: "push"
  payload_off: "off"
  retain: true

# The following switch wakes up the coffee machine
- platform: mqtt
  name: "Coffee Machine"
  state_topic: "home/tweek/status"
  command_topic: "home/tweek/cmd"
  qos: 2
  payload_on: "0"
  payload_off: "9"
  value_template: >
        {% if value == 'ready' %}
        0
        {% elif value == 'standby' %}
        9
        {% endif %}

# The following switches makes coffee      
- platform: mqtt
  name: "Espresso"
  state_topic: "home/tweek/status"
  command_topic: "home/tweek/cmd"
  qos: 2
  payload_on: "1"
  payload_off: ""
  value_template: '{{ value == "espresso" }}'

- platform: mqtt
  name: "Coffee"
  state_topic: "home/tweek/status"
  command_topic: "home/tweek/cmd"
  qos: 2
  payload_on: "2"
  payload_off: ""
  value_template: '{{ value == "coffee" }}'

